version: '3.9'

services:
  app:
    build:
      context: ./mysite
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite:/mysite
    ports:
      - "8000:8000"
    env_file:
      - ./mysite/.env
    environment:
      - DEBUG=1
